# Generated by Django 4.1.1 on 2022-10-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0002_alter_ichki_bolim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('narx', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('guarantee', models.CharField(max_length=50)),
                ('delivery', models.CharField(max_length=50)),
                ('availabilty', models.CharField(max_length=50)),
                ('chegirma', models.PositiveSmallIntegerField(default=0)),
                ('ichki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asosiyapp.ichki')),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='rasm-mahsulot')),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='asosiyapp.mahsulot')),
            ],
        ),
    ]
