# Generated by Django 4.1.1 on 2022-10-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0003_mahsulot_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='availabilty',
            field=models.BooleanField(default=True),
        ),
    ]
